version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: my_api_user
      POSTGRES_PASSWORD: my_api_password
      POSTGRES_DB: my_api_development
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rails_api_container
    depends_on:
      - db
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://my_api_user:my_api_password@db/my_api_development
      RAILS_ENV: development
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

volumes:
  postgres_data:
